name: Build and Deploy Website to CloudFront
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      BUCKET: csce412npham.xyz
      DIST: build
      REGION: us-east-1
      DIST_ID: E25ABXZ3LN2XWS

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Copy files to the production website using AWS CLI
        run: |
          aws s3 sync . s3://csce412npham.xyz --delete --cache-control "max-age=0, no-cache, no-store, must-revalidate"

      - name: Copy files to the production website website using AWS CLI
        run: |
          aws cloudfront create-invalidation \
          --distribution-id ${{ env.DIST_ID }} \
          --paths "/*" "assets/*"